import React,{useEffect,useState} from 'react';
import Sharing from './Sharing';
const pages=[['overview','◈','Обзор'],['character','✦','Мой персонаж'],['career','↗','Моя карьера']];
const skillName=(s:string)=>s.replace('SK_','').replaceAll('_',' ');
const statuses:any={completed:'Завершено',skipped:'Пропущено',declined:'Отклонено',pending:'Ожидает прохождения',overdue:'Срок прошёл'};
function Avatar({style}:any){return <svg className="character-art" viewBox="0 0 300 270" role="img" aria-label={style==='anime'?'Графический образ героя в плаще':'Графический образ футбольной формы'}><circle cx="150" cy="120" r="98" fill="none" stroke="currentColor" opacity=".2"/><circle cx="150" cy="120" r="76" fill="none" stroke="currentColor" strokeDasharray="3 10" opacity=".4"/>{style==='anime'?<><path d="M62 261 86 160 120 142 181 142 215 168 244 261Z" fill="#142f38" stroke="#a2dbc7"/><path d="m88 161 61 58 63-55-26 97H113Z" fill="#46756d"/><path d="m119 138 31 70 33-70" fill="#b4d8bf"/><path d="m119 79-8 31 17 36 28 13 30-26 8-38-18-30Z" fill="#dcba98"/><path d="m105 103 9-51 40-22 34 25 15 47-33-30-12 27-16-18-23 33Z" fill="#203e43" stroke="#98c4b6"/><path d="m122 169 28 46-17 46H86Z" fill="#234e49"/><path d="m184 167-34 48 20 46h51Z" fill="#315f58"/><path d="m150 218 8 13-8 13-8-13Z" fill="#ecc974"/></>:<><path d="m104 64-56 26 20 58 26-11-3 124h120l-5-124 27 11 20-58-57-26-46 15Z" fill="#e9d28e" stroke="#fff1bd" strokeWidth="2"/><path d="m123 66 27 17 27-17-7 30h-40Z" fill="#164f43"/><path d="M105 121h91v18h-91Z" fill="#174d41"/><text x="150" y="204" textAnchor="middle" fontSize="60" fontWeight="800" fill="#174d41">CQ</text><path d="m59 114 13 30m156 0 13-30" stroke="#164f43" strokeWidth="8"/></>}<path d="m42 43 4 10 10 4-10 4-4 10-4-10-10-4 10-4Z" fill="#efd184"/><path d="m257 181 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z" fill="#efd184"/></svg>}
function HeroCard({profile,style}:any){return <div className={'quest-card '+style}><div className="card-top"><span>CAREER EDITION</span><span>✦ PERSONAL</span></div><Avatar style={style}/><p className="card-archetype">{style==='anime'?'АРХИТЕКТОР БУДУЩЕГО':'СОЗДАТЕЛЬ ИГРЫ'}</p><h2>{profile.employee.role}</h2><div className="quest-card-bottom"><span>{profile.employee.grade}<small>ТЕКУЩИЙ ГРЕЙД</small></span><span>{profile.readiness}%<small>ГОТОВНОСТЬ К {profile.target_grade.toUpperCase()}</small></span></div></div>}
export default function EmployeeWorkspace({profile,result,style,theme,api,finish,busy,logout}:any){
 const valid=['overview','character','career'];
 const [page,setPage]=useState(valid.includes(location.hash.slice(1))?location.hash.slice(1):'overview');
 useEffect(()=>{function change(){const p=location.hash.slice(1);setPage(valid.includes(p)?p:'overview');}window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 function navigate(p:string){location.hash=p;setPage(p);window.scrollTo({top:0,behavior:'smooth'});}
 const completed=profile.history.filter((h:any)=>h.status==='completed');
 const doneSkills=Object.entries(profile.requirements).filter(([s,n]:any)=>(profile.employee.skills[s]||0)>=n).length;
 const pending=(profile.mandatory_training||[]).filter((t:any)=>t.status!=='completed').length;
 const primary=result?.recommendations[0];
 const Skills=()=> <div className="panel skill-panel"><div className="section-title"><h2>Карта навыков</h2><span>Цель: {profile.target_grade}</span></div>{Object.entries(profile.requirements).map(([s,n]:any)=><div className="skill" key={s}><div><span>{skillName(s)}</span><b>{profile.employee.skills[s]||0}<em> / {n}</em></b></div><progress aria-label={skillName(s)} max={n||5} value={Math.min(profile.employee.skills[s]||0,n)}/></div>)}</div>;
 const Recommendations=()=> <section><div className="section-title"><h2>Твой следующий шаг</h2><span>По профилю и истории</span></div>{!result?.recommendations.length&&<div className="panel empty">Подходящих шагов пока нет. Требования могут быть выполнены или каталог нужно дополнить.</div>}{result?.recommendations.map((r:any,i:number)=><article className={'recommendation '+(i===0?'priority':'')} key={r.event.id}><div className="recommendation-number">{String(i+1).padStart(2,'0')}</div><div className="recommendation-body"><div className="tag">{i===0?'РЕКОМЕНДУЕМ НАЧАТЬ ЗДЕСЬ':'АЛЬТЕРНАТИВНЫЙ ШАГ'} · {r.event.type}</div><h3>{r.event.title}</h3><div className="gain-chips">{r.factors.map((f:any)=><span key={f.skill}>+{f.effective_gain} {skillName(f.skill)}</span>)}</div><details><summary>Почему именно это?</summary>{r.factors.map((f:any)=><div className="reason" key={f.skill}><p><b>Карьерная цель:</b> {r.target_grade} требует {f.required} по {skillName(f.skill)}; вес критичности {f.criticality}.</p><p><b>Разрыв:</b> сейчас {f.current}; активность закрывает {f.effective_gain} из {f.gap} уровней.</p><p><b>История:</b> завершено {f.completed_count} из {f.history_count} связанных активностей. Оценка принятия с учётом формата — {Math.round(f.acceptance*100)}%. {f.history_count===0?'Истории навыка пока нет; используется сглаженная оценка.':''}</p></div>)}{i>0&&<p>Почему не первый выбор: оценка {r.score}, у первого варианта {result.recommendations[0].score}. При равенстве порядок определяется ID.</p>}</details><button disabled={busy||!profile.demo_mode} onClick={()=>finish(r.event.id)}>{profile.demo_mode?'Демо: завершить активность ↗':'Требуется подтверждение обучения'}</button></div></article>)}</section>;
 return <div className="workspace"><aside className="sidebar"><a className="side-brand" href="#overview" onClick={()=>navigate('overview')}><span className="brand-mark">cq<span>✦</span></span><span>career quest<small>ТВОЙ ПУТЬ К БОЛЬШЕМУ</small></span></a><div className="nav-caption">ЛИЧНОЕ ПРОСТРАНСТВО</div><nav aria-label="Основная навигация">{pages.map(([id,icon,label])=><a key={id} href={'#'+id} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}><span>{icon}</span>{label}{page===id&&<b>•</b>}</a>)}</nav><div className="nav-caption future-caption">В ПЛАНЕ РАЗВИТИЯ</div><div className="future-nav"><span>✧ AI-наставник</span><small>Скоро</small></div><div className="future-nav"><span>▧ Halyk Store</span><small>Скоро</small></div><div className="sidebar-note"><span>✦</span><p>Сравнивай себя<br/>только с собой вчера.</p><small>Твои достижения — твоя история.</small></div><div className="sidebar-account"><div className="mini-avatar">CQ</div><div><b>{profile.employee.employee_id}</b><small>{profile.employee.grade} · Личный кабинет</small></div><button className="logout-icon" onClick={logout} aria-label="Выйти">↪</button></div></aside>
 <div className="workspace-main"><header className="workspace-header"><span>Моё пространство <b>/ {pages.find(p=>p[0]===page)?.[2]}</b></span><div className="header-actions"><span className="private-badge">◉ Только для тебя</span><button className="mobile-logout" onClick={logout}>Выйти</button></div></header><main className="workspace-content"><section className="page-heading"><div><p className="eyebrow">{page==='overview'?'МАЛЕНЬКИЕ ШАГИ. БОЛЬШИЕ ПЕРЕМЕНЫ.':page==='character'?'ТВОЙ СТИЛЬ. ТВОЯ ИСТОРИЯ.':'ОТ ЦЕЛИ К КОНКРЕТНЫМ ШАГАМ.'}</p><h1>{page==='overview'?<>Твоя следующая глава<span>начинается здесь.</span></>:page==='character'?'Знакомься: твой герой.':'Построй свой путь.'}</h1><p>{page==='overview'?'Развивай навыки, открывай возможности и наблюдай за своим ростом.':page==='character'?'Один герой. Разные стили. Единый профессиональный прогресс.':'Понятная траектория к следующему грейду — в твоём темпе.'}</p></div><div className="chapter-badge"><span>ТВОЯ ЦЕЛЬ</span><b>{profile.target_grade}</b><small>Следующий грейд ↗</small></div></section>
 {page==='overview'&&<><div className="overview-grid"><section className="journey-banner"><div><span className="pill">✦ ПЕРСОНАЛЬНАЯ ТРАЕКТОРИЯ</span><h2>От {profile.employee.grade}<br/>к {profile.target_grade}.</h2><p>У каждого навыка есть следующий шаг.<br/>Найдём тот, который важен сейчас.</p><button className="gold-button" onClick={()=>navigate('career')}>Открыть мою траекторию <span>↗</span></button></div><div className="progress-orbit" style={{'--progress':profile.readiness+'%'} as React.CSSProperties}><div><strong>{profile.readiness}<small>%</small></strong><span>готовность<br/>по навыкам</span></div></div><span className="banner-decoration">✦</span></section><div className="overview-card"><HeroCard profile={profile} style={style}/><button className="text-button" onClick={()=>navigate('character')}>Мой персонаж <span>↗</span></button></div></div>
 <div className="stat-row"><div><span className="stat-icon">✓</span><p><strong>{completed.length}</strong><span>завершено активностей</span></p></div><div><span className="stat-icon">◈</span><p><strong>{doneSkills} <small>/ {Object.keys(profile.requirements).length}</small></strong><span>требований по навыкам закрыто</span></p></div><div><span className="stat-icon">↗</span><p><strong>{result?.recommendations.length||0}</strong><span>подходящих следующих шагов</span></p></div></div><div className="content-grid"><Recommendations/><aside><Skills/><div className="quiet-note"><span>◎</span><h3>Рост без гонки</h3><p>Здесь нет таблицы лидеров. Только твоя цель, твой прогресс и следующие возможности.</p></div></aside></div></>}
 {page==='character'&&<><div className="character-grid"><section><HeroCard profile={profile} style={style}/><div className="styles"><button aria-pressed={style==='anime'} onClick={()=>theme('anime')}>✦ Аниме</button><button aria-pressed={style==='football'} onClick={()=>theme('football')}>◉ Футбол</button></div><p className="hint">Смена стиля не меняет навыки и достижения.</p></section><div><Skills/><section className="panel"><p className="eyebrow">ЛИЧНАЯ КОЛЛЕКЦИЯ</p><h2>За каждым достижением — твой шаг</h2>{completed.length?<div className="achievement-grid">{completed.map((h:any,i:number)=><div key={i}><span>✧</span><b>{h.event_id}</b><small>{h.date}</small></div>)}</div>:<p>Первая завершённая активность появится здесь. Начни с подходящего шага в своей траектории.</p>}<p className="hint">Прогресс по навыкам не гарантирует повышение грейда.</p></section></div></div><Sharing request={api} style={style} revision={profile.revision}/></>}
 {page==='career'&&<><section className="roadmap panel"><div className="roadmap-node"><span>✓</span><div><small>СЕЙЧАС</small><b>{profile.employee.grade}</b></div></div><div className="roadmap-line"/><div className="roadmap-node active"><span>◎</span><div><small>В РАЗВИТИИ</small><b>Закрытие разрывов</b></div></div><div className="roadmap-line"/><div className="roadmap-node"><span>✦</span><div><small>ЦЕЛЬ</small><b>{profile.target_grade}</b></div></div></section><div className="content-grid"><Recommendations/><Skills/></div><section className="panel mandatory"><div className="section-title"><h2>Обязательное обучение</h2><span>{pending} ожидают завершения</span></div><p className="hint">Отдельно от добровольного развития. Без игровых наград.</p>{profile.mandatory_training?.length?profile.mandatory_training.map((t:any)=><div className="training" key={t.event_id}><h3>{t.title}</h3><p>{statuses[t.status]} · {t.due_date||'Без срока'}</p></div>):<p>✓ Сейчас нет назначенных обязательных курсов.</p>}</section><section className="panel"><h2>История твоих шагов</h2><div className="timeline">{profile.history.map((h:any,i:number)=><div key={i}><span className={'timeline-dot '+h.status}/><time>{h.date}</time><b>{h.event_id}</b><span>{statuses[h.status]||h.status}</span></div>)}</div></section></>}
 <footer>CAREER QUEST · NovaAI <span>Демонстрационные данные · Объяснения по проверяемым правилам</span></footer></main></div></div>
}
