import {tr} from './i18n';
import React, { useEffect, useState } from 'react';
import Sharing from './Sharing';
const pages = [['overview', '◈', 'Обзор'], ['character', '✦', 'Мой персонаж'], ['career', '↗', 'Моя карьера']];
const skillName = (s: string) => s.replace('SK_', '').replaceAll('_', ' ');
const statuses: any = { completed: 'Завершено', skipped: 'Пропущено', declined: 'Отклонено', pending: 'Ожидает прохождения', overdue: 'Срок прошёл' };
function Avatar({ style }: any) { return <svg className="character-art" viewBox="0 0 300 270" role="img" aria-label={tr(style === 'anime' ? 'Графический образ героя в плаще' : 'Графический образ футбольной формы')}><circle cx="150" cy="120" r="98" fill="none" stroke="currentColor" opacity=".2"/><circle cx="150" cy="120" r="76" fill="none" stroke="currentColor" strokeDasharray="3 10" opacity=".4"/>{tr(style === 'anime' ? <><path d="M62 261 86 160 120 142 181 142 215 168 244 261Z" fill="#142f38" stroke="#a2dbc7"/><path d="m88 161 61 58 63-55-26 97H113Z" fill="#46756d"/><path d="m119 138 31 70 33-70" fill="#b4d8bf"/><path d="m119 79-8 31 17 36 28 13 30-26 8-38-18-30Z" fill="#dcba98"/><path d="m105 103 9-51 40-22 34 25 15 47-33-30-12 27-16-18-23 33Z" fill="#203e43" stroke="#98c4b6"/><path d="m122 169 28 46-17 46H86Z" fill="#234e49"/><path d="m184 167-34 48 20 46h51Z" fill="#315f58"/><path d="m150 218 8 13-8 13-8-13Z" fill="#ecc974"/></> : <><path d="m104 64-56 26 20 58 26-11-3 124h120l-5-124 27 11 20-58-57-26-46 15Z" fill="#e9d28e" stroke="#fff1bd" strokeWidth="2"/><path d="m123 66 27 17 27-17-7 30h-40Z" fill="#164f43"/><path d="M105 121h91v18h-91Z" fill="#174d41"/><text x="150" y="204" textAnchor="middle" fontSize="60" fontWeight="800" fill="#174d41">{tr("CQ")}</text><path d="m59 114 13 30m156 0 13-30" stroke="#164f43" strokeWidth="8"/></>)}<path d="m42 43 4 10 10 4-10 4-4 10-4-10-10-4 10-4Z" fill="#efd184"/><path d="m257 181 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z" fill="#efd184"/></svg>; }
function HeroCard({ profile, style }: any) { return <div className={'quest-card ' + style}><div className="card-top"><span>{tr("CAREER EDITION")}</span><span>{tr("✦ PERSONAL")}</span></div><Avatar style={style}/><p className="card-archetype">{tr(style === 'anime' ? 'АРХИТЕКТОР БУДУЩЕГО' : 'СОЗДАТЕЛЬ ИГРЫ')}</p><h2>{tr(profile.employee.role)}</h2><div className="quest-card-bottom"><span>{tr(profile.employee.grade)}<small>{tr("ТЕКУЩИЙ ГРЕЙД")}</small></span><span>{tr(profile.readiness)}{tr("%")}<small>{tr("ГОТОВНОСТЬ К ")}{tr(profile.target_grade.toUpperCase())}</small></span></div></div>; }
export default function EmployeeWorkspace({ profile, result, style, theme, api, finish, busy, logout }: any) {
    const valid = ['overview', 'character', 'career'];
    const [page, setPage] = useState(valid.includes(location.hash.slice(1)) ? location.hash.slice(1) : 'overview');
    useEffect(() => { function change() { const p = location.hash.slice(1); setPage(valid.includes(p) ? p : 'overview'); } window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
    function navigate(p: string) { location.hash = p; setPage(p); window.scrollTo({ top: 0, behavior: 'smooth' }); }
    const completed = profile.history.filter((h: any) => h.status === 'completed');
    const doneSkills = Object.entries(profile.requirements).filter(([s, n]: any) => (profile.employee.skills[s] || 0) >= n).length;
    const pending = (profile.mandatory_training || []).filter((t: any) => t.status !== 'completed').length;
    const primary = result?.recommendations[0];
    const Skills = () => <div className="panel skill-panel"><div className="section-title"><h2>{tr("Карта навыков")}</h2><span>{tr("Цель: ")}{tr(profile.target_grade)}</span></div>{tr(Object.entries(profile.requirements).map(([s, n]: any) => <div className="skill" key={s}><div><span>{tr(skillName(s))}</span><b>{tr(profile.employee.skills[s] || 0)}<em>{tr(" / ")}{tr(n)}</em></b></div><progress aria-label={tr(skillName(s))} max={n || 5} value={Math.min(profile.employee.skills[s] || 0, n)}/></div>))}</div>;
    const Recommendations = () => <section><div className="section-title"><h2>{tr("Твой следующий шаг")}</h2><span>{tr("По профилю и истории")}</span></div>{tr(!result?.recommendations.length && <div className="panel empty">{tr("Подходящих шагов пока нет. Требования могут быть выполнены или каталог нужно дополнить.")}</div>)}{tr(result?.recommendations.map((r: any, i: number) => <article className={'recommendation ' + (i === 0 ? 'priority' : '')} key={r.event.id}><div className="recommendation-number">{tr(String(i + 1).padStart(2, '0'))}</div><div className="recommendation-body"><div className="tag">{tr(i === 0 ? 'РЕКОМЕНДУЕМ НАЧАТЬ ЗДЕСЬ' : 'АЛЬТЕРНАТИВНЫЙ ШАГ')}{tr(" · ")}{tr(r.event.type)}</div><h3>{tr(r.event.title)}</h3><div className="gain-chips">{tr(r.factors.map((f: any) => <span key={f.skill}>{tr("+")}{tr(f.effective_gain)} {tr(skillName(f.skill))}</span>))}</div><details><summary>{tr("Почему именно это?")}</summary>{tr(r.factors.map((f: any) => <div className="reason" key={f.skill}><p><b>{tr("Карьерная цель:")}</b> {tr(r.target_grade)}{tr(" требует ")}{tr(f.required)}{tr(" по ")}{tr(skillName(f.skill))}{tr("; вес критичности ")}{tr(f.criticality)}{tr(".")}</p><p><b>{tr("Разрыв:")}</b>{tr(" сейчас ")}{tr(f.current)}{tr("; активность закрывает ")}{tr(f.effective_gain)}{tr(" из ")}{tr(f.gap)}{tr(" уровней.")}</p><p><b>{tr("История:")}</b>{tr(" завершено ")}{tr(f.completed_count)}{tr(" из ")}{tr(f.history_count)}{tr(" связанных активностей. Оценка принятия с учётом формата — ")}{tr(Math.round(f.acceptance * 100))}{tr("%. ")}{tr(f.history_count === 0 ? 'Истории навыка пока нет; используется сглаженная оценка.' : '')}</p></div>))}{tr(i > 0 && <p>{tr("Почему не первый выбор: оценка ")}{tr(r.score)}{tr(", у первого варианта ")}{tr(result.recommendations[0].score)}{tr(". При равенстве порядок определяется ID.")}</p>)}</details><button disabled={busy || !profile.demo_mode} onClick={() => finish(r.event.id)}>{tr(profile.demo_mode ? 'Демо: завершить активность ↗' : 'Требуется подтверждение обучения')}</button></div></article>))}</section>;
    return <div className="workspace"><aside className="sidebar"><a className="side-brand" href="#overview" onClick={() => navigate('overview')}><span className="brand-mark">{tr("cq")}<span>{tr("✦")}</span></span><span>{tr("career quest")}<small>{tr("ТВОЙ ПУТЬ К БОЛЬШЕМУ")}</small></span></a><div className="nav-caption">{tr("ЛИЧНОЕ ПРОСТРАНСТВО")}</div><nav aria-label={tr("Основная навигация")}>{tr(pages.map(([id, icon, label]) => <a key={id} href={'#' + id} aria-current={page === id ? 'page' : undefined} onClick={() => navigate(id)}><span>{tr(icon)}</span>{tr(label)}{tr(page === id && <b>{tr("\u2022")}</b>)}</a>))}</nav><div className="nav-caption future-caption">{tr("В ПЛАНЕ РАЗВИТИЯ")}</div><div className="future-nav"><span>{tr("✧ AI-наставник")}</span><small>{tr("Скоро")}</small></div><div className="future-nav"><span>{tr("\u25A7 Halyk Store")}</span><small>{tr("Скоро")}</small></div><div className="sidebar-note"><span>{tr("✦")}</span><p>{tr("Сравнивай себя")}<br />{tr("только с собой вчера.")}</p><small>{tr("Твои достижения — твоя история.")}</small></div><div className="sidebar-account"><div className="mini-avatar">{tr("CQ")}</div><div><b>{tr(profile.employee.employee_id)}</b><small>{tr(profile.employee.grade)}{tr(" · Личный кабинет")}</small></div><button className="logout-icon" onClick={logout} aria-label={tr("Выйти")}>{tr("\u21AA")}</button></div></aside>
 <div className="workspace-main"><header className="workspace-header"><span>{tr("Моё пространство ")}<b>{tr("/ ")}{tr(pages.find(p => p[0] === page)?.[2])}</b></span><div className="header-actions"><span className="private-badge">{tr("\u25C9 Только для тебя")}</span><button className="mobile-logout" onClick={logout}>{tr("Выйти")}</button></div></header><main className="workspace-content"><section className="page-heading"><div><p className="eyebrow">{tr(page === 'overview' ? 'МАЛЕНЬКИЕ ШАГИ. БОЛЬШИЕ ПЕРЕМЕНЫ.' : page === 'character' ? 'ТВОЙ СТИЛЬ. ТВОЯ ИСТОРИЯ.' : 'ОТ ЦЕЛИ К КОНКРЕТНЫМ ШАГАМ.')}</p><h1>{tr(page === 'overview' ? <>{tr("Твоя следующая глава")}<span>{tr("начинается здесь.")}</span></> : page === 'character' ? 'Знакомься: твой герой.' : 'Построй свой путь.')}</h1><p>{tr(page === 'overview' ? 'Развивай навыки, открывай возможности и наблюдай за своим ростом.' : page === 'character' ? 'Один герой. Разные стили. Единый профессиональный прогресс.' : 'Понятная траектория к следующему грейду — в твоём темпе.')}</p></div><div className="chapter-badge"><span>{tr("ТВОЯ ЦЕЛЬ")}</span><b>{tr(profile.target_grade)}</b><small>{tr("Следующий грейд ↗")}</small></div></section>
 {tr(page === 'overview' && <><div className="overview-grid"><section className="journey-banner"><div><span className="pill">{tr("✦ ПЕРСОНАЛЬНАЯ ТРАЕКТОРИЯ")}</span><h2>{tr("От ")}{tr(profile.employee.grade)}<br />{tr("к ")}{tr(profile.target_grade)}{tr(".")}</h2><p>{tr("У каждого навыка есть следующий шаг.")}<br />{tr("Найдём тот, который важен сейчас.")}</p><button className="gold-button" onClick={() => navigate('career')}>{tr("Открыть мою траекторию ")}<span>{tr("↗")}</span></button></div><div className="progress-orbit" style={{ '--progress': profile.readiness + '%' } as React.CSSProperties}><div><strong>{tr(profile.readiness)}<small>{tr("%")}</small></strong><span>{tr("готовность")}<br />{tr("по навыкам")}</span></div></div><span className="banner-decoration">{tr("✦")}</span></section><div className="overview-card"><HeroCard profile={profile} style={style}/><button className="text-button" onClick={() => navigate('character')}>{tr("Мой персонаж ")}<span>{tr("↗")}</span></button></div></div>
 <div className="stat-row"><div><span className="stat-icon">{tr("✓")}</span><p><strong>{tr(completed.length)}</strong><span>{tr("завершено активностей")}</span></p></div><div><span className="stat-icon">{tr("◈")}</span><p><strong>{tr(doneSkills)} <small>{tr("/ ")}{tr(Object.keys(profile.requirements).length)}</small></strong><span>{tr("требований по навыкам закрыто")}</span></p></div><div><span className="stat-icon">{tr("↗")}</span><p><strong>{tr(result?.recommendations.length || 0)}</strong><span>{tr("подходящих следующих шагов")}</span></p></div></div><div className="content-grid"><Recommendations /><aside><Skills /><div className="quiet-note"><span>{tr("◎")}</span><h3>{tr("Рост без гонки")}</h3><p>{tr("Здесь нет таблицы лидеров. Только твоя цель, твой прогресс и следующие возможности.")}</p></div></aside></div></>)}
 {tr(page === 'character' && <><div className="character-grid"><section><HeroCard profile={profile} style={style}/><div className="styles"><button aria-pressed={style === 'anime'} onClick={() => theme('anime')}>{tr("✦ Аниме")}</button><button aria-pressed={style === 'football'} onClick={() => theme('football')}>{tr("\u25C9 Футбол")}</button></div><p className="hint">{tr("Смена стиля не меняет навыки и достижения.")}</p></section><div><Skills /><section className="panel"><p className="eyebrow">{tr("ЛИЧНАЯ КОЛЛЕКЦИЯ")}</p><h2>{tr("За каждым достижением — твой шаг")}</h2>{tr(completed.length ? <div className="achievement-grid">{tr(completed.map((h: any, i: number) => <div key={i}><span>{tr("✧")}</span><b>{tr(h.event_id)}</b><small>{tr(h.date)}</small></div>))}</div> : <p>{tr("Первая завершённая активность появится здесь. Начни с подходящего шага в своей траектории.")}</p>)}<p className="hint">{tr("Прогресс по навыкам не гарантирует повышение грейда.")}</p></section></div></div><Sharing request={api} style={style} revision={profile.revision}/></>)}
 {tr(page === 'career' && <><section className="roadmap panel"><div className="roadmap-node"><span>{tr("✓")}</span><div><small>{tr("СЕЙЧАС")}</small><b>{tr(profile.employee.grade)}</b></div></div><div className="roadmap-line"/><div className="roadmap-node active"><span>{tr("◎")}</span><div><small>{tr("В РАЗВИТИИ")}</small><b>{tr("Закрытие разрывов")}</b></div></div><div className="roadmap-line"/><div className="roadmap-node"><span>{tr("✦")}</span><div><small>{tr("ЦЕЛЬ")}</small><b>{tr(profile.target_grade)}</b></div></div></section><div className="content-grid"><Recommendations /><Skills /></div><section className="panel mandatory"><div className="section-title"><h2>{tr("Обязательное обучение")}</h2><span>{tr(pending)}{tr(" ожидают завершения")}</span></div><p className="hint">{tr("Отдельно от добровольного развития. Без игровых наград.")}</p>{tr(profile.mandatory_training?.length ? profile.mandatory_training.map((t: any) => <div className="training" key={t.event_id}><h3>{tr(t.title)}</h3><p>{tr(statuses[t.status])}{tr(" · ")}{tr(t.due_date || 'Без срока')}</p></div>) : <p>{tr("✓ Сейчас нет назначенных обязательных курсов.")}</p>)}</section><section className="panel"><h2>{tr("История твоих шагов")}</h2><div className="timeline">{tr(profile.history.map((h: any, i: number) => <div key={i}><span className={'timeline-dot ' + h.status}/><time>{tr(h.date)}</time><b>{tr(h.event_id)}</b><span>{tr(statuses[h.status] || h.status)}</span></div>))}</div></section></>)}
 <footer>{tr("CAREER QUEST · NovaAI ")}<span>{tr("Демонстрационные данные · Объяснения по проверяемым правилам")}</span></footer></main></div></div>;
}
